name: PaperBridge
version: '1.1.2'
main: com.yokito.paperbridge.bootstrap.PaperBridgePlugin
api-version: '1.21.11'
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    DiscordSRV:
      load: BEFORE
      required: false
commands:
  setDiscordNick:
    description: 設定您的 Discord 暱稱
    usage: /<command> <nickname>
    permission: paperbridge.setnick
  getDiscordNick:
    description: 查看目前的 Discord 暱稱
    usage: /<command> [player]
    permission: paperbridge.getnick
permissions:
  paperbridge.getnick.self:
    description: 允許玩家查看自己的暱稱。
    default: true
  paperbridge.getnick.others:
    description: 允許玩家查看他人的暱稱。
    default: true
  paperbridge.setnick:
    description: 允許玩家設定自己的暱稱。
    default: true
